import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import { context, statement, retrieval } from '../fixtures/fixture.ts';
const check=process.argv.includes('--check');
const notices=await readFile('THIRD_PARTY_NOTICES.md','utf8');
const hashes={};
async function artifact(path,content){if(check){if(await readFile(path,'utf8')!==content)throw new Error(`Stale generated artifact: ${path}`);}else{await mkdir(resolve(path,'..'),{recursive:true});await writeFile(path,content);}hashes[path]=createHash('sha256').update(content).digest('hex');}
async function code(snippet){const result=await build({stdin:{contents:`import * as C from './src/index.ts'; import * as W from './src/workflow.ts'; async function execute(){${snippet}};var checkerAnswer=await execute.call(this);`,resolveDir:process.cwd(),sourcefile:'node-entry.js'},bundle:true,write:false,format:'esm',platform:'browser',target:'es2022',minifySyntax:true,minifyWhitespace:true,minifyIdentifiers:false,legalComments:'inline'});return result.outputFiles[0].text+'\nreturn checkerAnswer;';}
let serial=0;
function graph(name){return{name,nodes:[],connections:{},settings:{executionOrder:'v1',saveDataSuccessExecution:'none',saveDataErrorExecution:'none',saveManualExecutions:false,saveExecutionProgress:false,timezone:'UTC'},active:false,pinData:{},meta:{templateCredsSetupCompleted:false}};}
function node(g,name,type,version,parameters,extra={}){const index=serial++;const n={id:createHash('sha256').update(name).digest('hex').slice(0,32),name,type:`n8n-nodes-base.${type}`,typeVersion:version,position:[(index%6)*300,Math.floor(index/6)*230],parameters,...extra};g.nodes.push(n);return name;}
function edge(g,from,to,output=0){g.connections[from]??={main:[]};while(g.connections[from].main.length<=output)g.connections[from].main.push([]);g.connections[from].main[output].push({node:to,type:'main',index:0});}
async function js(g,name,snippet){return node(g,name,'code',2,{jsCode:await code(snippet)});}
function route(g,name){return node(g,name,'switch',3.4,{mode:'expression',numberOutputs:4,output:'={{ $json.route }}'});}
const waitOptions={limitWaitTime:true,limitType:'afterTimeInterval',resumeAmount:24,resumeUnit:'hours'};
function form(g,name,title){return node(g,name,'form',2.5,{operation:'page',defineForm:'json',jsonOutput:'={{ JSON.stringify($json.fields) }}',...waitOptions,options:{formTitle:title,buttonLabel:'Continue'}},{webhookId:createHash('sha256').update(name).digest('hex').slice(0,32)});}
async function reports(g,source){
 const render=await js(g,'Create report files',`const s=$json;const report=W.makeReport(s);const files=C.reportFiles(report);const binary={};let i=0;for(const [name,text] of Object.entries(files)){const mime=name.endsWith('.html')?'text/html':name.endsWith('.json')?'application/json':name.endsWith('.csv')?'text/csv':'text/plain';binary['file'+i++]={data:Buffer.from(text,'utf8').toString('base64'),fileName:name,mimeType:mime};}return [{json:{status:report.status,summary:C.summaryHtml(report),fields:[W.field('summary','','html',{html:C.summaryHtml(report)})],counts:report.counts},binary}];`);
 edge(g,source,render);
 const zip=node(g,'Package report ZIP','compression',1.1,{operation:'compress',binaryPropertyName:'={{ Object.keys($binary).join(",") }}',outputFormat:'zip',fileName:'supplier-statement-report.zip',binaryPropertyOutput:'reportZip'});edge(g,render,zip);
 const summary=form(g,'Review result summary','Supplier statement check result');edge(g,zip,summary);
 const restore=await js(g,'Return prepared ZIP',`const prepared=$('Package report ZIP').first();return [{json:prepared.json,binary:prepared.binary}];`);edge(g,summary,restore);
 const end=node(g,'Download report','form',2.5,{operation:'completion',respondWith:'returnBinary',inputDataFieldName:'reportZip',completionTitle:'Download your report ZIP',completionMessage:'Open report.html to read results. No accounting entries were posted and no emails were sent.',...waitOptions,options:{}},{webhookId:'checker-report-download'});edge(g,restore,end);
 const status=node(g,'Final run status','switch',3.4,{mode:'expression',numberOutputs:2,output:'={{ $("Create report files").first().json.status === "completed" ? 0 : 1 }}'});edge(g,end,status);
 const error=node(g,'Mark failed run','stopAndError',1,{errorType:'errorMessage',errorMessage:'The check did not complete. See the diagnostic report. No matching conclusions are valid.'});edge(g,status,error,1);return render;
}
const demo=graph('Xero Supplier Statement Checker — synthetic demo');
const dstart=node(demo,'Start synthetic demo','formTrigger',2.6,{authentication:'n8nUserAuth',requireExecuteAccess:true,formTitle:'Try the supplier statement checker',formDescription:'Synthetic demonstration. No Xero or OpenAI credentials are required.',formFields:{values:[]},responseMode:'onReceived',options:{path:'supplier-checker-demo',includeUserInOutput:false}},{webhookId:'supplier-checker-demo'});
const ddata=await js(demo,'Synthetic fixture',`return [{json:{context:${JSON.stringify(context)},lines:${JSON.stringify(statement)},retrieval:${JSON.stringify(retrieval)}}}];`);edge(demo,dstart,ddata);await reports(demo,ddata);
node(demo,'Third-party licenses','stickyNote',1,{content:notices,height:800,width:700});
await artifact('workflows/synthetic-demo.json',JSON.stringify(demo,null,2)+'\n');
serial=0;const live=graph('Xero Supplier Statement Checker — read-only');
node(live,'Setup instructions','stickyNote',1,{content:'## Setup (n8n 2.39.6+)\n1. Configure tenant ID below.\n2. Create generic OAuth2 credentials with offline_access accounting.contacts.read accounting.invoices.read. Assign to both Xero HTTP nodes. Do not use the built-in Xero credential (it requests write scopes).\n3. Optional: assign OpenAI header credential, enable its HTTP node and enable PDFs.\n4. Publish the form. Operator must sign in to n8n.\n5. Review README retention settings before real data.\nNo data is posted to Xero; no emails are sent.',height:480,width:540});
const start=node(live,'Upload statement','formTrigger',2.6,{authentication:'n8nUserAuth',requireExecuteAccess:true,formTitle:'Check a supplier statement',formDescription:'Upload a UTF-8 CSV or text-based PDF. One organization, supplier and currency per run. PDFs use optional OpenAI extraction and require your confirmation.',formFields:{values:[{fieldLabel:'Statement file',fieldName:'statement',fieldType:'file',multipleFiles:false,acceptFileTypes:'.csv,.pdf',requiredField:true},{fieldLabel:'Statement date',fieldName:'statementDate',fieldType:'date',requiredField:true},{fieldLabel:'Currency (ISO code)',fieldName:'currency',fieldType:'text',defaultValue:'GBP',requiredField:true},...['dateFormat','numberFormat','delimiter','includeDraft'].map((fieldName,index)=>({fieldName,fieldLabel:['Date format','Number format','CSV delimiter','Include an unsent follow-up draft'][index],fieldType:'dropdown',fieldOptions:{values:[['ISO','DMY','MDY'],['decimal_dot','decimal_comma'],['comma','semicolon','tab'],['No','Yes']][index].map(option=>({option}))},requiredField:true}))]},responseMode:'onReceived',options:{path:'supplier-statement-checker',includeUserInOutput:false}},{webhookId:'supplier-statement-checker'});
const config=node(live,'Operator configuration','set',3.4,{mode:'manual',assignments:{assignments:[{id:'tenant',name:'tenantId',type:'string',value:'CONFIGURE_XERO_TENANT_ID'},{id:'model',name:'model',type:'string',value:'gpt-5.6-terra'},{id:'ai',name:'aiEnabled',type:'boolean',value:false}]},includeOtherFields:true,options:{}});edge(live,start,config);
const init=await js(live,'Validate upload',`const raw=$json;const now=new Date().toISOString();const ctx={runId:String($execution.id),tenantId:raw.tenantId,supplierId:'00000000-0000-0000-0000-000000000000',supplierName:'Not selected',currency:String(raw.currency??'').trim().toUpperCase(),statementDate:raw.statementDate,fileName:'unknown',fileHash:'0'.repeat(64),startedAt:now,inputType:'csv',includeDraft:raw.includeDraft==='Yes'};const s={context:ctx,lines:[],contacts:[],contactPages:[],page:1,attempt:0,route:2,delay:1,model:raw.model,aiEnabled:raw.aiEnabled===true,numberFormat:raw.numberFormat,dateFormat:raw.dateFormat,delimiter:raw.delimiter==='semicolon'?';':raw.delimiter==='tab'?'\t':',',retrieval:{tenantId:raw.tenantId,contactId:ctx.supplierId,resource:'Invoices',type:'ACCPAY',startedAt:now,finishedAt:now,pages:[],bills:[]}};try{if(!C.UUID.test(ctx.tenantId))C.fail('CONFIGURATION_REQUIRED','Set the tenant ID in Operator configuration.');const keys=Object.keys($binary??{});if(keys.length!==1)C.fail('ONE_FILE_REQUIRED','Upload exactly one file.');const binary=$input.first().binary[keys[0]];const data=await this.helpers.getBinaryDataBuffer(0,keys[0]);ctx.fileName=binary.fileName??'statement';if(data.length>C.LIMITS.bytes)C.fail('FILE_LIMIT','Maximum upload size is 10 MiB.');ctx.fileHash=require('crypto').createHash('sha256').update(data).digest('hex');const pdf=data.subarray(0,5).toString()==='%PDF-';ctx.inputType=pdf?'pdf':'csv';if(!pdf&&!ctx.fileName.toLowerCase().endsWith('.csv'))C.fail('UNSUPPORTED_FILE','Only text PDFs and UTF-8 CSV are supported.');C.validateContext(ctx);if(!pdf)s.csvText=data.toString('utf8');return[{json:s,binary:{statement:binary}}];}catch(error){return[{json:W.workflowError(s,error)}];}`);edge(live,config,init);
const initRoute=route(live,'Upload valid?');edge(live,init,initRoute);
const failEntry=await js(live,'Prepare diagnostic',`return [{json:$json}];`);
edge(live,initRoute,failEntry,3);
async function apiLoop(resource,from){
 const snapshot=await js(live,`${resource} request state`,`return [{json:$json}];`);edge(live,from,snapshot);
 const query=resource==='Contacts'?[{name:'page',value:'={{ $json.page }}'},{name:'pageSize',value:'100'},{name:'order',value:'ContactID ASC'},{name:'includeArchived',value:'true'}]:[{name:'page',value:'={{ $json.page }}'},{name:'pageSize',value:'100'},{name:'where',value:'={{ \'Type=="ACCPAY" AND Contact.ContactID==guid("\' + $json.context.supplierId + \'")\' }}'},{name:'order',value:'InvoiceID ASC'},{name:'Statuses',value:'DRAFT,SUBMITTED,AUTHORISED,PAID,VOIDED,DELETED'}];
 const http=node(live,`Fetch Xero ${resource}`,'httpRequest',4.4,{method:'GET',url:`https://api.xero.com/api.xro/2.0/${resource}`,authentication:'genericCredentialType',genericAuthType:'oAuth2Api',sendHeaders:true,headerParameters:{parameters:[{name:'xero-tenant-id',value:'={{ $json.context.tenantId }}'},{name:'Accept',value:'application/json'}]},sendQuery:true,queryParameters:{parameters:query},options:{timeout:60000,redirect:{redirect:{followRedirects:false}},response:{response:{fullResponse:true,neverError:true,responseFormat:'text',outputPropertyName:'data'}}}},{onError:'continueRegularOutput'});edge(live,snapshot,http);
 const accept=await js(live,`Validate ${resource} page`,`const s=$('${resource} request state').item.json;return [{json:W.acceptPage(s,$json,'${resource}',new Date().toISOString())}];`);edge(live,http,accept);
 const decision=route(live,`${resource} retrieval status`);edge(live,accept,decision);
 const delay=node(live,`Respect ${resource} rate limits`,'wait',1.1,{resume:'timeInterval',amount:'={{ $json.delay }}',unit:'seconds'},{webhookId:`checker-${resource.toLowerCase()}-retry`});edge(live,decision,delay,0);edge(live,decision,delay,1);edge(live,delay,snapshot);edge(live,decision,failEntry,3);
 return {snapshot,decision};
}
// API-loop entry connection uses output 2 (validated/complete) rather than output 0.
const contactLoop=await apiLoop('Contacts',initRoute);live.connections[initRoute].main[2]=live.connections[initRoute].main[0];live.connections[initRoute].main[0]=[];
const supplierForm=form(live,'Select supplier','Select the supplier');edge(live,contactLoop.decision,supplierForm,2);
const supplierAccept=await js(live,'Confirm supplier',`return [{json:W.selectSupplier($('Validate Contacts page').item.json,$json)}];`);edge(live,supplierForm,supplierAccept);
const inputRoute=route(live,'CSV or PDF');edge(live,supplierAccept,inputRoute);
const mapping=form(live,'Map CSV columns','Map statement columns');edge(live,inputRoute,mapping,0);
const mapped=await js(live,'Extract CSV rows',`return [{json:W.mapCsv($('Confirm supplier').item.json,$json,new Date().toISOString())}];`);edge(live,mapping,mapped);
const mappedRoute=route(live,'CSV extraction valid?');edge(live,mapped,mappedRoute);edge(live,mappedRoute,failEntry,3);edge(live,inputRoute,failEntry,3);
const restorePdf=await js(live,'Restore PDF upload',`const upload=$('Validate upload').first();return [{json:$json,binary:upload.binary}];`);edge(live,inputRoute,restorePdf,1);
const pdf=node(live,'Extract text from every PDF page','extractFromFile',1.1,{operation:'pdf',binaryPropertyName:'statement',options:{joinPages:false,maxPages:51,keepSource:'json'}},{onError:'continueRegularOutput'});edge(live,restorePdf,pdf);
const pages=await js(live,'Prepare PDF requests',`const s=$('Restore PDF upload').first().json;try{if($json.error)C.fail('PDF_EXTRACTION_FAILED','Use an unencrypted text-based PDF or export UTF-8 CSV.');const pages=C.pdfPages($json);return pages.map((text,index)=>({json:{state:s,page:index+1,pageText:text,pageCount:pages.length,request:C.extractionRequest(text,index+1,s.model)}}));}catch(error){return[{json:{state:W.workflowError(s,error),route:3}}];}`);edge(live,pdf,pages);
const pdfValid=route(live,'PDF text valid?');edge(live,pages,pdfValid);live.nodes.find(n=>n.name===pdfValid).parameters.output='={{ $json.route === 3 ? 3 : 2 }}';
const pdfFail=await js(live,'PDF diagnostic',`return [{json:$json.state}];`);edge(live,pdfValid,pdfFail,3);edge(live,pdfFail,failEntry);
const ai=node(live,'Extract PDF fields with OpenAI','httpRequest',4.4,{method:'POST',url:'https://api.openai.com/v1/responses',authentication:'genericCredentialType',genericAuthType:'httpHeaderAuth',sendBody:true,specifyBody:'json',jsonBody:'={{ JSON.stringify($json.request) }}',options:{timeout:180000,response:{response:{responseFormat:'json'}}}},{disabled:true,retryOnFail:true,maxTries:3,waitBetweenTries:5000,onError:'continueRegularOutput'});edge(live,pdfValid,ai,2);
const gather=await js(live,'Validate PDF extraction',`const requests=$('Prepare PDF requests').all();const outputs=$input.all();const s=requests[0].json.state;try{if(outputs.length!==requests.length)C.fail('INCOMPLETE_EXTRACTION','Not all PDF pages have responses.');s.lines=[];s.pdfWarnings=[];for(let i=0;i<requests.length;i++){const p=requests[i].json;const parsed=C.parseExtraction(outputs[i].json,p.pageText,p.page,s.context.fileName,s.context.currency);s.lines.push(...parsed.lines);s.pdfWarnings.push(...parsed.warnings);}s.context.extraction={model:s.model,promptVersion:C.PROMPT_VERSION,pageCount:requests.length};return[{json:W.reviewFields(s,new Date().toISOString())}];}catch(error){return[{json:W.workflowError(s,error)}];}`);edge(live,ai,gather);
const extractedRoute=route(live,'PDF extraction valid?');edge(live,gather,extractedRoute);edge(live,extractedRoute,failEntry,3);
const reviewState=await js(live,'Statement review state',`return [{json:$json}];`);edge(live,mappedRoute,reviewState,2);edge(live,extractedRoute,reviewState,2);
const reviewForm=form(live,'Confirm extracted statement','Review and confirm every statement row');edge(live,reviewState,reviewForm);
const reviewed=await js(live,'Validate operator confirmation',`return [{json:W.acceptReview($('Statement review state').first().json,$json,new Date().toISOString())}];`);edge(live,reviewForm,reviewed);
const reviewRoute=route(live,'Statement confirmed?');edge(live,reviewed,reviewRoute);edge(live,reviewRoute,failEntry,3);
const invoiceLoop=await apiLoop('Invoices',reviewRoute);live.connections[reviewRoute].main[2]=live.connections[reviewRoute].main[0];live.connections[reviewRoute].main[0]=[];
const final=await js(live,'Check complete retrieval',`return [{json:$json}];`);edge(live,invoiceLoop.decision,final,2);edge(live,failEntry,final);
await reports(live,final);
node(live,'Third-party licenses','stickyNote',1,{content:notices,height:800,width:700});
await artifact('workflows/xero-supplier-statement-checker.json',JSON.stringify(live,null,2)+'\n');
// Headless fixture uses the exact same report nodes, without waiting on forms.
const cli=structuredClone(demo);cli.name='Checker fixture verification';cli.nodes=cli.nodes.filter(n=>!['Review result summary','Return prepared ZIP','Download report'].includes(n.name));cli.nodes[0]={...cli.nodes[0],type:'n8n-nodes-base.manualTrigger',typeVersion:1,parameters:{}};delete cli.connections['Package report ZIP'];delete cli.connections['Review result summary'];delete cli.connections['Return prepared ZIP'];delete cli.connections['Download report'];edge(cli,'Package report ZIP','Final run status');
await artifact('workflows/fixture-verification.json',JSON.stringify(cli,null,2)+'\n');
await artifact('workflows/checksums.json',JSON.stringify(hashes,null,2)+'\n');
console.log(check?'Generated workflows match source.':'Generated live, demo and verification workflows.');
